name: Push Image to Amazon ECR

# when tagging action success
on:
  workflow_run:
    workflows: ["Create Release and Tag"]
    types:
      - completed

env:
  AWS_REGION: ap-northeast-2

jobs:
  if_workflow_success:
    name: Build and Push
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get previous tag-version
      id: previous_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0
    
    - name: Set Tag Version
      id: tag
      uses: actions/github-script@v4
      with:
        script: |
          const tagVersion = "${{ steps.previous_tag.outputs.tag }}".replace('v', '')
          core.setOutput('tag', tagVersion)
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and Push to AWS ECR
      id: build_image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        ECR_REPOSITORY: taxi-front
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Push iamge : $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG and latest"
